language: java

jdk:
# start building with JDK 11 for testing and analysis
- openjdk11

cache:
  directories:
  - $HOME/.m2

addons:
  sonarcloud:
    organization: "sebasbaumh"
    token:
      secure: "oE2J4Y7lUVe+xNdaQpuYBanYMK2yaudz6TNnKCReN2RpIclUtkpV9qP0I5FFDXmVszIGgmcc8+ljsXzjmoBPBMgebEb1uIpwbR+nF39qd+baecL61qsWW3Epn5r4+hfbstgiWjQg7C0gJeKf3TgtcWZLWv84hLtyVt0OUnkNQyZ20T7AasW6xqRL0fCnrKcaify7LHiB8UfDU9OE/AO0YRfJ+aCu+ELFV73rzjXQlXZDOFR6YHYzVj48zdsXXfTtrlUBcvh/q0i6kPqgAlgMgC1lRI6BFosJQNskoNPRp2h1GOmIhdV7fhQrgOGCOuO4KkTZTbBDyONVcf3kNHG9VJm560FsC4ZASL0gzmhkp5JbiHMWIFNU/SzNgK2XpkNdIkHyMe5vq3IzNUQzX0eyAuyYrLg6tIZtBwmRNsbNRYWBQeIZwxCh1c8i95TZP7/P6/DVgAf5lqANuOv6O9ugyKXCxPu8jek2MEITUD2psISDS4v2WEicRSvEzNZZqh5CdmYdO0aLx5WBNa5FvnqswN2lhe5niZZzkuDypCMud5YdrJTZKj3N9hrWYN4UNtmt5zficSJ3iPEu0L8ClZWyGBjxc2WwVp8kYDpRrJi+r6FPl6Z5XM37WDrucRUdg+y/uwVIeArv0F9RceL66qqcfSVm5/Rw31fT9Hai8ok+pcw="

script:
  # the following command line builds the project, runs the tests with coverage and then executes the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sebasbaumh_postgis-java-ng
